on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - uses: actions/dependency-review-action@v4
        with:
          allow-licenses: MIT
